/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Course = IDL.Record({
  'fee' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
});
export const TutorProfile = IDL.Record({
  'bio' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'photoId' : IDL.Text,
});
export const Time = IDL.Int;
export const Video = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'thumbnailId' : IDL.Text,
  'description' : IDL.Text,
  'uploadedAt' : Time,
  'videoFileId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AcademyProfile = IDL.Record({
  'about' : IDL.Text,
  'foundedYear' : IDL.Nat,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Enrollment = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([Course], [], []),
  'addTutor' : IDL.Func([TutorProfile], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCourse' : IDL.Func([], [], []),
  'deleteTutor' : IDL.Func([], [], []),
  'deleteVideo' : IDL.Func([], [], []),
  'getAcademyInfo' : IDL.Func([], [IDL.Vec(AcademyProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getExternalBlobs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExternalBlob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'submitContact' : IDL.Func([Enrollment], [], []),
  'updateAcademyInfo' : IDL.Func([AcademyProfile], [], []),
  'updateCourse' : IDL.Func([Course], [], []),
  'updateTutor' : IDL.Func([TutorProfile], [], []),
  'updateVideo' : IDL.Func([Video], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Course = IDL.Record({
    'fee' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
  });
  const TutorProfile = IDL.Record({
    'bio' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'photoId' : IDL.Text,
  });
  const Time = IDL.Int;
  const Video = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'thumbnailId' : IDL.Text,
    'description' : IDL.Text,
    'uploadedAt' : Time,
    'videoFileId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AcademyProfile = IDL.Record({
    'about' : IDL.Text,
    'foundedYear' : IDL.Nat,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Enrollment = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([Course], [], []),
    'addTutor' : IDL.Func([TutorProfile], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCourse' : IDL.Func([], [], []),
    'deleteTutor' : IDL.Func([], [], []),
    'deleteVideo' : IDL.Func([], [], []),
    'getAcademyInfo' : IDL.Func([], [IDL.Vec(AcademyProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getExternalBlobs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExternalBlob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'submitContact' : IDL.Func([Enrollment], [], []),
    'updateAcademyInfo' : IDL.Func([AcademyProfile], [], []),
    'updateCourse' : IDL.Func([Course], [], []),
    'updateTutor' : IDL.Func([TutorProfile], [], []),
    'updateVideo' : IDL.Func([Video], [], []),
  });
};

export const init = ({ IDL }) => { return []; };