/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademyProfile {
  'about' : string,
  'foundedYear' : bigint,
  'tagline' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Course {
  'fee' : bigint,
  'title' : string,
  'duration' : string,
  'subject' : string,
  'description' : string,
}
export interface Enrollment {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface TutorProfile {
  'bio' : string,
  'subject' : string,
  'name' : string,
  'photoId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'title' : string,
  'subject' : string,
  'thumbnailId' : string,
  'description' : string,
  'uploadedAt' : Time,
  'videoFileId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[Course], undefined>,
  'addTutor' : ActorMethod<[TutorProfile], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCourse' : ActorMethod<[], undefined>,
  'deleteTutor' : ActorMethod<[], undefined>,
  'deleteVideo' : ActorMethod<[], undefined>,
  'getAcademyInfo' : ActorMethod<[], Array<AcademyProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Enrollment>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getExternalBlobs' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getTutors' : ActorMethod<[], Array<TutorProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExternalBlob' : ActorMethod<[string, ExternalBlob], undefined>,
  'submitContact' : ActorMethod<[Enrollment], undefined>,
  'updateAcademyInfo' : ActorMethod<[AcademyProfile], undefined>,
  'updateCourse' : ActorMethod<[Course], undefined>,
  'updateTutor' : ActorMethod<[TutorProfile], undefined>,
  'updateVideo' : ActorMethod<[Video], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];